parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'production'

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: BuildJob
  displayName: 'Build and Test'
  steps:
  - script: echo "Running Build Step"
    displayName: 'Build Step'

  - script: echo "Running Test Step"
    displayName: 'Test Step'

- job: DeployJob
  displayName: 'Deploy'
  dependsOn: BuildJob
  variables:
    environment: ${{ parameters.environment }}
  steps:
  - script: echo "Running Deployment Step to $environment"
    displayName: 'Deployment Step'

  - task: PowerShell@2  # Use PowerShell task instead of ShellScript@2 for Windows
    displayName: 'Custom PowerShell Script'
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem C:\Manual\  # List files in the C:\Manual directory
        Get-Content C:\Manual\Sample1.sh  # Display content of Sample1.sh
