parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'production'

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: BuildJob
  displayName: 'Build and Test'
  steps:
  - script: echo "Running Build Step"
    displayName: 'Build Step'

  - script: echo "Running Test Step"
    displayName: 'Test Step'

- job: DeployJob
  displayName: 'Deploy'
  dependsOn: BuildJob
  variables:
    environment: ${{ parameters.environment }}
  steps:
  - script: echo "Running Deployment Step to $environment"
    displayName: 'Deployment Step'

  - task: ShellScript@2
    displayName: 'Custom Shell Script'
    inputs:
      scriptPath: 'C:\Users\jatin.dalla\OneDrive - Duck Creek Technologies LLC\Desktop\Sample.ps1'  # Path to your shell script
      args: 'NO'  # Optional arguments to pass to the script

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
      MaxArtifactSize: 1
